export interface SubjectVideoLink {
  id: string;
  title: string;
  subject:
    | "Computer Science"
    | "AI & Machine Learning"
    | "Mathematics"
    | "Physics"
    | "Engineering"
    | "General";
  channel: string;
  duration: string;
  readTimeMinutes: number;
  url: string;
  videoId: string;
  thumbnailUrl: string;
  description: string;
  tags: string[];
  keyTopics: string[];
}

export const SUBJECT_VIDEO_LINKS: SubjectVideoLink[] = [
  // --- COMPUTER SCIENCE ---
  {
    id: "cs_cs50",
    title: "Harvard CS50 – Introduction to Computer Science & Algorithm Complexity",
    subject: "Computer Science",
    channel: "freeCodeCamp.org / Harvard",
    duration: "55:00",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=8mAITcNt710",
    videoId: "8mAITcNt710",
    thumbnailUrl: "https://i.ytimg.com/vi/8mAITcNt710/hqdefault.jpg",
    description: "Foundational computational principles, Big-O asymptotic notation, memory hierarchies, and core data structures.",
    tags: ["Algorithms", "Big-O", "Data Structures", "Memory"],
    keyTopics: ["Binary Representation", "Asymptotic Analysis", "Arrays vs Linked Lists", "Memory Layout"],
  },
  {
    id: "cs_os",
    title: "Operating Systems: Concurrency, Virtual Memory & Kernel Space",
    subject: "Computer Science",
    channel: "MIT OpenCourseWare",
    duration: "48:15",
    readTimeMinutes: 7,
    url: "https://www.youtube.com/watch?v=WUvTyaaNkzM",
    videoId: "WUvTyaaNkzM",
    thumbnailUrl: "https://i.ytimg.com/vi/WUvTyaaNkzM/hqdefault.jpg",
    description: "Deep dive into system calls, context switching, virtual page translation (TLB), and mutex synchronization.",
    tags: ["Operating Systems", "Virtual Memory", "Concurrency", "Kernel"],
    keyTopics: ["Ring 0 vs Ring 3", "Page Tables & MMU", "Thread Synchronization", "Deadlocks"],
  },
  {
    id: "cs_dsa",
    title: "Data Structures & Algorithms: Trees, Graphs & Dynamic Programming",
    subject: "Computer Science",
    channel: "Fireship / Tech Acad",
    duration: "35:40",
    readTimeMinutes: 5,
    url: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
    videoId: "RBSGKlAvoiM",
    thumbnailUrl: "https://i.ytimg.com/vi/RBSGKlAvoiM/hqdefault.jpg",
    description: "Core algorithms: Binary Search Trees, BFS/DFS graph exploration, Heaps, and Dynamic Programming memoization.",
    tags: ["DSA", "Graphs", "Trees", "Sorting"],
    keyTopics: ["Graph Traversals", "Binary Heaps", "Dynamic Programming", "Time Complexity"],
  },
  {
    id: "cs_sysdesign",
    title: "System Design Fundamentals: Load Balancing, Caching & Microservices",
    subject: "Computer Science",
    channel: "Gaurav Sen",
    duration: "42:10",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=pkYVOmU3wgA",
    videoId: "pkYVOmU3wgA",
    thumbnailUrl: "https://i.ytimg.com/vi/pkYVOmU3wgA/hqdefault.jpg",
    description: "High-level architecture design: vertical vs horizontal scaling, consistent hashing, and database sharding.",
    tags: ["System Design", "Scalability", "Caching", "Databases"],
    keyTopics: ["Horizontal Scaling", "Consistent Hashing", "Message Queues", "CAP Theorem"],
  },

  // --- AI & MACHINE LEARNING ---
  {
    id: "aiml_nn",
    title: "Neural Networks & Backpropagation Fundamentals",
    subject: "AI & Machine Learning",
    channel: "3Blue1Brown",
    duration: "19:12",
    readTimeMinutes: 8,
    url: "https://www.youtube.com/watch?v=aircAruvnKk",
    videoId: "aircAruvnKk",
    thumbnailUrl: "https://i.ytimg.com/vi/aircAruvnKk/hqdefault.jpg",
    description: "Visual and mathematical intuition for multi-layer perceptrons, cost surfaces, and gradient descent updates.",
    tags: ["Deep Learning", "Calculus", "Optimization", "Weights & Biases"],
    keyTopics: ["Neuron Activations", "Cost Gradients", "Multivariable Chain Rule", "Learning Rate"],
  },
  {
    id: "aiml_trans",
    title: "Transformers & Attention Mechanism (Attention Is All You Need)",
    subject: "AI & Machine Learning",
    channel: "StatQuest with Josh Starmer",
    duration: "24:30",
    readTimeMinutes: 7,
    url: "https://www.youtube.com/watch?v=kCc8FmEb1nY",
    videoId: "kCc8FmEb1nY",
    thumbnailUrl: "https://i.ytimg.com/vi/kCc8FmEb1nY/hqdefault.jpg",
    description: "Self-attention matrix computation, Positional encodings, Multi-head attention, and transformer encoders/decoders.",
    tags: ["Transformers", "Attention", "LLMs", "NLP"],
    keyTopics: ["Queries, Keys, Values", "Scaled Dot-Product", "Multi-Head Attention", "Positional Embeddings"],
  },
  {
    id: "aiml_full",
    title: "Machine Learning for Beginners: Regression, Classification & Clustering",
    subject: "AI & Machine Learning",
    channel: "freeCodeCamp.org",
    duration: "52:20",
    readTimeMinutes: 8,
    url: "https://www.youtube.com/watch?v=i_LwzRVP7bg",
    videoId: "i_LwzRVP7bg",
    thumbnailUrl: "https://i.ytimg.com/vi/i_LwzRVP7bg/hqdefault.jpg",
    description: "Comprehensive introduction to supervised vs unsupervised learning, loss functions, and evaluation metrics.",
    tags: ["Machine Learning", "Scikit-Learn", "Regression", "Metrics"],
    keyTopics: ["Linear Regression", "Logistic Classification", "K-Means Clustering", "Overfitting & Regularization"],
  },
  {
    id: "aiml_genai",
    title: "Generative AI and Large Language Models (LLMs) Architecture",
    subject: "AI & Machine Learning",
    channel: "Google Cloud Tech",
    duration: "22:15",
    readTimeMinutes: 5,
    url: "https://www.youtube.com/watch?v=IHZwWFHWa-w",
    videoId: "IHZwWFHWa-w",
    thumbnailUrl: "https://i.ytimg.com/vi/IHZwWFHWa-w/hqdefault.jpg",
    description: "Principles of Generative AI, foundational models, RLHF, prompt engineering, and parameter-efficient fine tuning.",
    tags: ["Generative AI", "LLMs", "Fine-Tuning", "Prompt Engineering"],
    keyTopics: ["Foundational Models", "Prompt Engineering", "Temperature & Top-P", "Hallucination Mitigation"],
  },

  // --- MATHEMATICS ---
  {
    id: "math_linalg",
    title: "Essence of Linear Algebra: Vectors, Matrices & Transformations",
    subject: "Mathematics",
    channel: "3Blue1Brown",
    duration: "18:05",
    readTimeMinutes: 5,
    url: "https://www.youtube.com/watch?v=fNk_zzaMoSs",
    videoId: "fNk_zzaMoSs",
    thumbnailUrl: "https://i.ytimg.com/vi/fNk_zzaMoSs/hqdefault.jpg",
    description: "Geometric intuition for basis vectors, linear coordinate transforms, matrix products, and determinants.",
    tags: ["Linear Algebra", "Matrices", "Determinants", "Eigenvectors"],
    keyTopics: ["Basis Vectors î and ĵ", "Linear Transformations", "Determinants as Area Scaling", "Matrix Non-Commutativity"],
  },
  {
    id: "math_calc",
    title: "The Essence of Calculus: Derivatives, Integrals & Fundamental Theorem",
    subject: "Mathematics",
    channel: "3Blue1Brown",
    duration: "21:30",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=9vKqVkMQHKk",
    videoId: "9vKqVkMQHKk",
    thumbnailUrl: "https://i.ytimg.com/vi/9vKqVkMQHKk/hqdefault.jpg",
    description: "Derivatives as instantaneous rates of change, Riemann summation integrals, and the fundamental link between them.",
    tags: ["Calculus", "Derivatives", "Integrals", "Limits"],
    keyTopics: ["Geometric Rate of Change", "Power Rule Derivation", "Riemann Integral Sums", "Fundamental Theorem"],
  },
  {
    id: "math_discrete",
    title: "Discrete Mathematics: Sets, Propositional Logic & Mathematical Proofs",
    subject: "Mathematics",
    channel: "TrevTutor",
    duration: "38:40",
    readTimeMinutes: 7,
    url: "https://www.youtube.com/watch?v=tyDKR4FG3Yw",
    videoId: "tyDKR4FG3Yw",
    thumbnailUrl: "https://i.ytimg.com/vi/tyDKR4FG3Yw/hqdefault.jpg",
    description: "Mathematical induction, boolean propositions, truth tables, set cardinality, and graph theory axioms.",
    tags: ["Discrete Math", "Logic", "Induction", "Set Theory"],
    keyTopics: ["Propositional Equivalence", "Proof by Induction", "De Morgan's Laws", "Graph Traversals"],
  },
  {
    id: "math_prob",
    title: "Probability & Statistics: Bayes' Theorem, Random Variables & Distributions",
    subject: "Mathematics",
    channel: "MIT OpenCourseWare",
    duration: "45:00",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=m47SffnC9dQ",
    videoId: "m47SffnC9dQ",
    thumbnailUrl: "https://i.ytimg.com/vi/m47SffnC9dQ/hqdefault.jpg",
    description: "Conditional probability, Bayes' Rule, discrete vs continuous distributions, and Central Limit Theorem.",
    tags: ["Probability", "Statistics", "Bayes Rule", "Distributions"],
    keyTopics: ["Conditional Probability", "Bayes' Theorem", "Normal Distribution", "Central Limit Theorem"],
  },

  // --- PHYSICS ---
  {
    id: "phys_mech",
    title: "Classical Mechanics: Newton's Laws, Circular Motion & Gravitation",
    subject: "Physics",
    channel: "Prof. Walter Lewin / MIT Physics",
    duration: "50:25",
    readTimeMinutes: 8,
    url: "https://www.youtube.com/watch?v=wWnfJ0-xXRE",
    videoId: "wWnfJ0-xXRE",
    thumbnailUrl: "https://i.ytimg.com/vi/wWnfJ0-xXRE/hqdefault.jpg",
    description: "MIT 8.01 lecture explaining force vectors, conservation of momentum, mechanical energy, and planetary orbits.",
    tags: ["Classical Mechanics", "Newton's Laws", "Energy", "Momentum"],
    keyTopics: ["Inertial Frames", "Conservation of Momentum", "Gravitational Field Potential", "Hooke's Law"],
  },
  {
    id: "phys_quantum",
    title: "Quantum Mechanics: Double Slit Experiment & Wave-Particle Duality",
    subject: "Physics",
    channel: "Veritasium",
    duration: "21:45",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=p7bzE1E5PMY",
    videoId: "p7bzE1E5PMY",
    thumbnailUrl: "https://i.ytimg.com/vi/p7bzE1E5PMY/hqdefault.jpg",
    description: "Wave function collapse, Heisenberg uncertainty principle, quantum superposition, and photon interference patterns.",
    tags: ["Quantum Mechanics", "Wave-Particle", "Superposition", "Photons"],
    keyTopics: ["Double Slit Interference", "Heisenberg Uncertainty Principle", "Schrödinger Wavefunction", "Measurement Problem"],
  },
  {
    id: "phys_thermo",
    title: "Thermodynamics & The Arrow of Time: Entropy Explained",
    subject: "Physics",
    channel: "Kurzgesagt / PBS Space Time",
    duration: "16:20",
    readTimeMinutes: 5,
    url: "https://www.youtube.com/watch?v=DxL2HoqLbyA",
    videoId: "DxL2HoqLbyA",
    thumbnailUrl: "https://i.ytimg.com/vi/DxL2HoqLbyA/hqdefault.jpg",
    description: "The 4 Laws of Thermodynamics, microstates, statistical entropy (Boltzmann equation), and irreversible processes.",
    tags: ["Thermodynamics", "Entropy", "Heat Engines", "Statistical Physics"],
    keyTopics: ["Second Law of Thermodynamics", "Boltzmann Entropy S = k log W", "Heat Engines & Carnot Efficiency", "Thermal Equilibrium"],
  },
  {
    id: "phys_em",
    title: "Electromagnetism: Maxwell's Equations & Electromagnetic Wave Propagation",
    subject: "Physics",
    channel: "MIT Physics / The Science Asylum",
    duration: "34:10",
    readTimeMinutes: 7,
    url: "https://www.youtube.com/watch?v=XRr1kaXKBsU",
    videoId: "XRr1kaXKBsU",
    thumbnailUrl: "https://i.ytimg.com/vi/XRr1kaXKBsU/hqdefault.jpg",
    description: "Gauss's laws, Faraday's induction, Ampere-Maxwell law, and how coupled electric and magnetic fields travel at light speed.",
    tags: ["Electromagnetism", "Maxwell Equations", "Magnetic Fields", "Induction"],
    keyTopics: ["Gauss's Law for E and B", "Faraday Induction", "Displacement Current", "Speed of Light Derivation"],
  },

  // --- ENGINEERING ---
  {
    id: "eng_circuits",
    title: "Electrical Engineering: Circuit Analysis, Ohm's & Kirchhoff's Laws",
    subject: "Engineering",
    channel: "MIT OpenCourseWare",
    duration: "46:50",
    readTimeMinutes: 7,
    url: "https://www.youtube.com/watch?v=fJbm14x8S-A",
    videoId: "fJbm14x8S-A",
    thumbnailUrl: "https://i.ytimg.com/vi/fJbm14x8S-A/hqdefault.jpg",
    description: "Nodal and mesh analysis, Thévenin and Norton equivalent circuits, capacitors, inductors, and AC impedance.",
    tags: ["Circuits", "Kirchhoff", "Electrical", "Electronics"],
    keyTopics: ["Kirchhoff's Current & Voltage Laws", "Nodal Voltage Method", "Thévenin Equivalent", "RC & RLC Transients"],
  },
  {
    id: "eng_thermo",
    title: "Mechanical Engineering: Understanding Thermodynamics & Engine Cycles",
    subject: "Engineering",
    channel: "The Efficient Engineer",
    duration: "25:35",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=kYv9d5NnZvg",
    videoId: "kYv9d5NnZvg",
    thumbnailUrl: "https://i.ytimg.com/vi/kYv9d5NnZvg/hqdefault.jpg",
    description: "Otto, Diesel, and Brayton power cycles, PV diagrams, specific heats, and thermodynamic efficiency optimization.",
    tags: ["Mechanical", "Engine Cycles", "Thermodynamics", "Efficiency"],
    keyTopics: ["Otto & Diesel Cycles", "Pressure-Volume Diagrams", "Thermal Efficiency", "Compressor Work"],
  },
  {
    id: "eng_structures",
    title: "Structural Engineering: Mechanics of Materials, Stress & Strain",
    subject: "Engineering",
    channel: "Real Engineering",
    duration: "22:40",
    readTimeMinutes: 5,
    url: "https://www.youtube.com/watch?v=y3qsf9_u_8U",
    videoId: "y3qsf9_u_8U",
    thumbnailUrl: "https://i.ytimg.com/vi/y3qsf9_u_8U/hqdefault.jpg",
    description: "Tensile, compressive and shear stresses, Young's modulus, stress-strain curves, and factor of safety.",
    tags: ["Structures", "Stress & Strain", "Civil Engineering", "Materials"],
    keyTopics: ["Stress-Strain Elastic Curve", "Young's Modulus E", "Shear Stress & Bending Moments", "Factor of Safety"],
  },
  {
    id: "eng_fluids",
    title: "Fluid Mechanics: Bernoulli's Principle, Navier-Stokes & Aerodynamics",
    subject: "Engineering",
    channel: "The Efficient Engineer",
    duration: "28:15",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=P3gn1-N3-18",
    videoId: "P3gn1-N3-18",
    thumbnailUrl: "https://i.ytimg.com/vi/P3gn1-N3-18/hqdefault.jpg",
    description: "Conservation of mass and momentum in fluids, laminar vs turbulent flows, Reynolds number, and airfoil lift.",
    tags: ["Fluid Mechanics", "Bernoulli", "Aerodynamics", "Navier-Stokes"],
    keyTopics: ["Continuity Equation", "Bernoulli's Energy Conservation", "Reynolds Number Re", "Boundary Layer Separation"],
  },

  // --- GENERAL ---
  {
    id: "gen_python",
    title: "Python Tutorial for Beginners - Full Course (with Notes & Practice Questions)",
    subject: "General",
    channel: "Apna College",
    duration: "45:00",
    readTimeMinutes: 6,
    url: "https://www.youtube.com/watch?v=vLqTf2b6GZw",
    videoId: "vLqTf2b6GZw",
    thumbnailUrl: "https://i.ytimg.com/vi/vLqTf2b6GZw/hqdefault.jpg",
    description: "Complete Python programming fundamentals: variables, conditionals, loops, functions, lists, and file handling.",
    tags: ["Python", "Programming", "Coding", "Beginner"],
    keyTopics: ["Data Types & Variables", "Control Structures & Loops", "Functions & Scoping", "Lists, Tuples & Dictionaries"],
  },
  {
    id: "gen_learning",
    title: "How We Learn: Cognitive Science, Active Recall & Spaced Repetition",
    subject: "General",
    channel: "Ali Abdaal / Veritasium",
    duration: "18:40",
    readTimeMinutes: 4,
    url: "https://www.youtube.com/watch?v=IlU-zDU6aQ0",
    videoId: "IlU-zDU6aQ0",
    thumbnailUrl: "https://i.ytimg.com/vi/IlU-zDU6aQ0/hqdefault.jpg",
    description: "Evidence-based revision protocols: the testing effect, flashcards, Feynman technique, and forgetting curve mitigation.",
    tags: ["Cognitive Science", "Study Skills", "Active Recall", "Productivity"],
    keyTopics: ["Ebbinghaus Forgetting Curve", "Active Recall Testing Effect", "Spaced Repetition Intervals", "The Feynman Technique"],
  },
  {
    id: "gen_web",
    title: "Web Architecture: How Browsers, HTTP/HTTPS & Servers Communicate",
    subject: "General",
    channel: "freeCodeCamp.org",
    duration: "31:10",
    readTimeMinutes: 5,
    url: "https://www.youtube.com/watch?v=HGOBQPFzWKo",
    videoId: "HGOBQPFzWKo",
    thumbnailUrl: "https://i.ytimg.com/vi/HGOBQPFzWKo/hqdefault.jpg",
    description: "DNS resolution, TLS handshake, TCP/IP packets, HTTP request-response cycles, and browser DOM rendering engines.",
    tags: ["Web", "Networking", "HTTP", "Browsers"],
    keyTopics: ["DNS Lookup Process", "TLS/SSL Cryptographic Handshake", "HTTP Methods & Status Codes", "DOM & CSSOM Rendering"],
  },
];

export function getSubjectVideos(
  subject?: "All" | "Computer Science" | "AI & Machine Learning" | "Mathematics" | "Physics" | "Engineering" | "General" | string
): SubjectVideoLink[] {
  if (!subject || subject === "All") {
    return SUBJECT_VIDEO_LINKS;
  }
  return SUBJECT_VIDEO_LINKS.filter((v) => v.subject === subject);
}
